queue_rules:
  - name: default
    conditions:
      - status-success=tox (3.6, ubuntu-20.04)
      - status-success=tox (3.9, ubuntu-latest)
      - status-success=integration (rhel-8)

pull_request_rules:
  - name: automatic merge for master when CI passes
    conditions:
      - or:
        - author=ktdreyer
        - author=hluk
      - status-success=tox (3.6, ubuntu-20.04)
      - status-success=tox (3.9, ubuntu-latest)
      - status-success=integration (rhel-8)
      - base=master
    actions:
      queue:
        name: default
        method: rebase
