queue_rules:
  - name: default
    conditions:
      - status-success=tox (2.7, ubuntu-20.04)
      - status-success=tox (3.6, ubuntu-20.04)
      - status-success=tox (3.9, ubuntu-latest)
      - status-success=integration (rhel-7)

pull_request_rules:
  - name: automatic merge for master when CI passes
    conditions:
      - author=ktdreyer
      - status-success=tox (2.7, ubuntu-20.04)
      - status-success=tox (3.6, ubuntu-20.04)
      - status-success=tox (3.9, ubuntu-latest)
      - status-success=integration (rhel-7)
      - base=master
    actions:
      queue:
        name: default
        method: rebase
