pull_request_rules:
  - name: automatic merge for master when CI passes
    conditions:
      - author=ktdreyer
      - status-success=Travis CI - Pull Request
      - base=master
    actions:
      merge:
        strict: true
        strict_method: rebase
        method: rebase
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}

