language: python
python:
- 2.7
- 3.6
- 3.7
install: pip install tox-travis
script: tox

jobs:
  include:
  - python: 3.8
    after_success:
    - pip install coveralls
    - coveralls

  - name: test collection build
    install: pip install ansible
    script: tests/integration/collection.sh
    addons:
     apt:
       packages:
       - pandoc

cache:
  directories:
  - $HOME/.cache/pip
