language: python
python:
- 2.7
- 3.6
install: pip install tox-travis
script: tox

jobs:
  include:
  - python: 3.7
    after_success:
    - pip install coveralls
    - coveralls

cache:
  directories:
  - $HOME/.cache/pip
