name: tests

on: [push, pull_request]

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version:
        - 2.7
        - 3.6
        - 3.8
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libkrb5-dev
        pip install tox
    - name: Test with tox
      run: |
        PY=py$(echo ${{ matrix.python-version }} | tr -d ".")
        tox -e ${PY} -- --cov-report=xml tests
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  test-collection:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch base branches for version calculation
      run: |
        git fetch origin master:master || :
        [ -z $GITHUB_BASE_REF ] || git fetch origin $GITHUB_BASE_REF:$GITHUB_BASE_REF
    - uses: actions/setup-python@v2
    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install pandoc
    - name: Test collection build
      run: tests/integration/collection.sh
